brace_style = "PreferSameLine"
control_brace_style = "ClosingNextLine"
enum_discrim_align_threshold = 50
fn_args_layout = "Compressed"
fn_single_line = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
max_width = 150
merge_derives = false
normalize_comment = true
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
short_array_element_width_threshold = 20
spaces_around_ranges = true
struct_field_align_threshold = 20
trailing_comma = "Always"
